---
title: "Gene Ontology"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


############################# GENE ONTOLOGY #############################


### Libraries loading ###

```{r}
library(biomaRt)
library(limma)
library(stringr)
library(GO.db)
library(org.Hs.eg.db)
library(clusterProfiler)
library(MOMA)
```


### Gene list ###

```{r}
TF_list = read.csv("Results/TF_list.csv")
mygenes = as.character(TF_list$x)
length(mygenes)

TF_total = read.csv("/home/crct2112/Documents/GRN/git2/GRN_inference/Data/TF_names_v_1.01.txt")
TF_total = as.character(TF_total$AC008770.3) #format :
```


### Format conversion ###

```{r}
#Convert from hugo gene names to entrez ids

#mapHugo(c("ADNP","ADNP2","AEBP1"))
TF_total_ID = mapHugo(TF_total)
```

### Remove version from ensembl id ###

```{r}
#mygenes=str_split_fixed(mygenes,"\\.",2)[,1]
```

### ID conversion Ensembl to Entrez ###

```{r}
# library("TxDb.Hsapiens.UCSC.hg38.knownGene")
# geneHg38.gr <- genes(TxDb.Hsapiens.UCSC.hg38.knownGene,columns="gene_id")
# gene_id <- geneHg38.gr$gene_id
# orgDBgenes <- select(org.Hs.eg.db,keys = gene_id,columns = "SYMBOL",keytype = "ENTREZID")
# geneHg38.gr$SYMBOL <- orgDBgenes[match(gene_id,orgDBgenes[,1]),2]
# myentrez=geneHg38.gr$gene_id[which(geneHg38.gr$SYMBOL %in% mygenes)]
```



### BioMart ###

```{r}
ensembl = useEnsembl(biomart="genes")
datasets <- listDatasets(ensembl)
datasets
ensembl = useEnsembl(biomart="genes", dataset="hsapiens_gene_ensembl")

listAttributes(ensembl)
genes.with.id=getBM(attributes=c("hgnc_symbol", "entrezgene_id"), values=mygenes, mart=ensembl)

id = genes.with.id[which(genes.with.id$hgnc_symbol %in% mygenes),]
nrow(id)
myentrez = unique(id$entrezgene)

length(mygenes) #140 genes
length(myentrez) #133 genes


```



### Gene Ontology ###
```{r}
goana = goana(de=myentrez, geneid=myentrez, FDR=0.95, species="Hs", universe = TF_total_ID)
View(goana)
```


#GO Plot
```{r}
compGO <- compareCluster(geneCluster     = list(genes=myentrez),
                         fun           = "enrichGO",
                         OrgDb         = 'org.Hs.eg.db',
                         ont           = 'BP',
                         pvalueCutoff  = 0.05,
                         pAdjustMethod = "BH",
                         universe = TF_total_ID)
dotplot(compGO, showCategory = 10, title = "Gene Ontology Enrichment Analysis")
```



### KEGG Ontology ###
```{r}
kegga = kegga(de=myentrez, geneid=myentrez, FDR=0.95, species="Hs", universe = TF_total_ID)
View(kegga)
```


#KEGG Plot
```{r}
compKEGG <- compareCluster(geneCluster   = list(genes=myentrez),
                           fun           = "enrichKEGG",
                           pvalueCutoff  = 0.25,
                           pAdjustMethod = "BH",
                           universe = TF_total_ID) 
dotplot(compKEGG, showCategory = 15, title = "KEGG Pathway Enrichment Analysis")
```



### Keep only "BP" ontology and pvalue < 0.05 then sort by pvalue ###
```{r}
goana = goana[which(goana$Ont == "BP" & goana$P.DE < 0.05),]
goana = goana[order(goana$P.DE),]
kegga = kegga[order(kegga$P.DE),]
```



## Which genes are concerned by a GO ID
```{r}
genes.with.id2 = getBM(attributes=c("ensembl_gene_id","hgnc_symbol","go_id", "description"), values=mygenes, mart=ensembl)
id2 = genes.with.id2[which(genes.with.id2$hgnc_symbol %in% mygenes),]

id2[which(id2$go_id=="GO:0016779"),c(2,4)]
```


### Export to csv file ###
```{r}
write.csv(goana, "Results/Gene_Ontology.csv", quote=F)
write.csv(kegga, "Results/KEGG_Pathway.csv", quote=F)
```

